# Generated by Django 3.2.5 on 2021-07-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('transaction_date', models.DateField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
