# Generated by Django 3.2.1 on 2021-07-04 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bankapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=122)),
                ('rname', models.CharField(max_length=122)),
                ('amount', models.IntegerField()),
                ('tdate', models.DateField(verbose_name=datetime.datetime(2021, 7, 5, 5, 25, 38, 916176))),
            ],
        ),
    ]
