# Generated by Django 3.2.1 on 2021-07-05 00:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bankapp', '0003_alter_transaction_tdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='money',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tdate',
            field=models.DateField(verbose_name=datetime.datetime(2021, 7, 5, 5, 31, 40, 367679)),
        ),
    ]
